// ── Orchestrator ────────────────────────────────────────────

export const orchestrationFlow = {
  title: "Myeloid Orchestrator",
  nodes: [
    { id: "input", label: "Parsed Report", type: "input", description: "Blasts, genetics, cytogenetics, qualifiers" },
    { id: "aml", label: "AML Classifier", type: "classifier", description: "WHO or ICC" },
    { id: "error_check", label: "Error?", type: "decision" },
    { id: "return_error", label: "Return Error", type: "output" },
    { id: "bcrabl", label: "BCR::ABL1+ and blasts <20%?", type: "decision" },
    { id: "cml", label: "CML Classifier", type: "classifier" },
    { id: "return_cml", label: "Return CML", type: "output" },
    { id: "definitive", label: "AML definitive?", type: "decision" },
    { id: "return_aml", label: "Return AML", type: "output" },
    { id: "mds", label: "MDS Classifier", type: "classifier" },
    { id: "cmml_check", label: "Monocytosis?", type: "decision", description: "MDS gate detected monocyte_cytosis" },
    { id: "return_mds", label: "Return MDS", type: "output" },
    { id: "cmml", label: "CMML Classifier", type: "classifier", description: "If CMML data provided; otherwise returns sentinel to UI" },
    { id: "return_cmml", label: "Return CMML", type: "output" },
  ],
  edges: [
    { from: "input", to: "aml" },
    { from: "aml", to: "error_check" },
    { from: "error_check", to: "return_error", label: "Yes" },
    { from: "error_check", to: "bcrabl", label: "No" },
    { from: "bcrabl", to: "cml", label: "Yes" },
    { from: "cml", to: "return_cml" },
    { from: "bcrabl", to: "definitive", label: "No" },
    { from: "definitive", to: "return_aml", label: "Yes" },
    { from: "definitive", to: "mds", label: "Non-AML" },
    { from: "mds", to: "cmml_check" },
    { from: "cmml_check", to: "return_mds", label: "No" },
    { from: "cmml_check", to: "cmml", label: "Yes" },
    { from: "cmml", to: "return_cmml" },
  ],
};

// ── AML WHO 2022 ────────────────────────────────────────────
// Matches classify_AML_WHO2022() step order exactly

export const amlWhoFlow = {
  title: "AML Classification — WHO 2022",
  nodes: [
    { id: "input", label: "Patient Data", type: "input", description: "Blasts %, genetics, cytogenetics" },
    { id: "validate", label: "Validate Blasts", type: "action", description: "Must be 0-100%" },
    { id: "cebpa_ambig", label: "CEBPA ambiguous?", type: "decision", description: "CEBPA detected but bZIP status unclear" },
    { id: "return_cebpa_confirm", label: "Needs CEBPA confirmation", type: "output" },
    { id: "step1", label: "Step 1: AML-defining abnormality?", type: "decision", description: "PML::RARA, NPM1, RUNX1::RUNX1T1, CBFB::MYH11, DEK::NUP214, KMT2A, MECOM, NUP98, CEBPA (bZIP/biallelic, >=20%), BCR::ABL1 (>=20%)" },
    { id: "return_aml_defining", label: "AML with [abnormality]", type: "output" },
    { id: "blast_under_20", label: "Blasts < 20%?", type: "decision" },
    { id: "erythroid", label: "Erythroid leukaemia?", type: "decision", description: ">=80% erythroid + >=30% proerythroblasts" },
    { id: "return_erythroid", label: "Acute Erythroid Leukaemia", type: "output" },
    { id: "return_non_aml", label: "Not AML", type: "output", description: "Sentinel → MDS classifier" },
    { id: "step2", label: "Step 2: MDS-related mutations?", type: "decision", description: "ASXL1, BCOR, EZH2, SF3B1, SRSF2, STAG2, U2AF1, ZRSR2" },
    { id: "return_mds_related", label: "AML, myelodysplasia related", type: "output" },
    { id: "step3", label: "Step 3: MDS-related cytogenetics?", type: "decision", description: "Complex, del(5q), -7, del(7q), i(17q), del(12p), -13, del(20q)... (excludes +8)" },
    { id: "step3a", label: "Step 3a: Prior MDS/MPN history?", type: "decision", description: ">3 months ago" },
    { id: "step3b", label: "Step 3b: Special entities?", type: "decision", description: "Basophilic, panmyelosis+fibrosis, Down syndrome/GATA1" },
    { id: "return_special", label: "AML with specific features", type: "output" },
    { id: "step4", label: "Step 4: FAB differentiation", type: "decision", description: "M0-M7 morphology mapping" },
    { id: "return_diff", label: "AML by differentiation", type: "output", description: "e.g. AML with maturation" },
    { id: "return_nos", label: "AML, unknown differentiation", type: "output" },
  ],
  edges: [
    { from: "input", to: "validate" },
    { from: "validate", to: "cebpa_ambig" },
    { from: "cebpa_ambig", to: "return_cebpa_confirm", label: "Yes" },
    { from: "cebpa_ambig", to: "step1", label: "No" },
    { from: "step1", to: "return_aml_defining", label: "Yes" },
    { from: "step1", to: "blast_under_20", label: "No" },
    { from: "blast_under_20", to: "erythroid", label: "Yes (<20%)" },
    { from: "erythroid", to: "return_erythroid", label: "Confirmed" },
    { from: "erythroid", to: "return_non_aml", label: "No" },
    { from: "blast_under_20", to: "step2", label: "No (>=20%)" },
    { from: "step2", to: "return_mds_related", label: "Yes" },
    { from: "step2", to: "step3", label: "No" },
    { from: "step3", to: "return_mds_related", label: "Yes" },
    { from: "step3", to: "step3a", label: "No" },
    { from: "step3a", to: "return_mds_related", label: "Yes" },
    { from: "step3a", to: "step3b", label: "No" },
    { from: "step3b", to: "return_special", label: "Yes" },
    { from: "step3b", to: "step4", label: "No" },
    { from: "step4", to: "return_diff", label: "FAB code found" },
    { from: "step4", to: "return_nos", label: "None" },
  ],
};

// ── AML ICC 2022 ────────────────────────────────────────────
// Matches classify_AML_ICC2022() step order exactly

export const amlIccFlow = {
  title: "AML Classification — ICC 2022",
  nodes: [
    { id: "input", label: "Patient Data", type: "input", description: "Blasts %, genetics, cytogenetics" },
    { id: "validate", label: "Validate Blasts", type: "action", description: "Must be 0-100%" },
    { id: "cebpa_ambig", label: "CEBPA ambiguous?", type: "decision", description: "CEBPA detected but bZIP status unclear" },
    { id: "return_cebpa_confirm", label: "Needs CEBPA confirmation", type: "output" },
    { id: "step1", label: "Step 1: AML-defining abnormality?", type: "decision", description: "Requires blasts >=10%. Includes BCR::ABL1 (>=20%), extended RARA/KMT2A partners, rare fusions" },
    { id: "return_aml_defining", label: "AML with [abnormality]", type: "output" },
    { id: "step2", label: "Step 2: TP53 multi-hit?", type: "decision", description: "2x mutations, +del(17p), +LOH, >=50% VAF, or >=10% VAF + complex karyotype" },
    { id: "tp53_blasts", label: "Blast level?", type: "decision" },
    { id: "return_tp53_low", label: "Not AML", type: "output", description: "Blasts <10% → MDS" },
    { id: "return_tp53_mid", label: "MDS/AML with mutated TP53", type: "output", description: "Blasts 10-19%" },
    { id: "return_tp53_high", label: "AML with mutated TP53", type: "output", description: "Blasts >=20%" },
    { id: "step3", label: "Step 3: MDS-related mutations?", type: "decision", description: "ASXL1, BCOR, EZH2, RUNX1, SF3B1, SRSF2, STAG2, U2AF1, ZRSR2" },
    { id: "mut_blasts", label: "Blast level?", type: "decision" },
    { id: "return_mut_low", label: "Not AML", type: "output", description: "Blasts <10% → MDS" },
    { id: "return_mut_mid", label: "MDS/AML with mutations", type: "output", description: "Blasts 10-19%" },
    { id: "return_mut_high", label: "AML, myelodysplasia related", type: "output", description: "Blasts >=20%" },
    { id: "step4", label: "Step 4: MDS-related cytogenetics?", type: "decision", description: "WHO list + trisomy 8 (+8)" },
    { id: "cyto_blasts", label: "Blast level?", type: "decision" },
    { id: "return_cyto_low", label: "Not AML", type: "output", description: "Blasts <10% → MDS" },
    { id: "return_cyto_mid", label: "MDS/AML with cytogenetics", type: "output", description: "Blasts 10-19%" },
    { id: "return_cyto_high", label: "AML, myelodysplasia related", type: "output", description: "Blasts >=20%" },
    { id: "step4a", label: "Step 4a: Prior MDS/MPN history?", type: "decision", description: ">3 months ago" },
    { id: "step5", label: "Step 5: Default fallback", type: "decision", description: "Blast-stratified" },
    { id: "return_nos_low", label: "Not AML", type: "output", description: "Blasts <10% → MDS" },
    { id: "return_nos_mid", label: "MDS/AML, NOS", type: "output", description: "Blasts 10-19%" },
    { id: "return_nos_high", label: "AML, NOS", type: "output", description: "Blasts >=20%" },
  ],
  edges: [
    { from: "input", to: "validate" },
    { from: "validate", to: "cebpa_ambig" },
    { from: "cebpa_ambig", to: "return_cebpa_confirm", label: "Yes" },
    { from: "cebpa_ambig", to: "step1", label: "No" },
    { from: "step1", to: "return_aml_defining", label: "Yes" },
    { from: "step1", to: "step2", label: "No" },
    { from: "step2", to: "tp53_blasts", label: "Yes" },
    { from: "tp53_blasts", to: "return_tp53_low", label: "<10%" },
    { from: "tp53_blasts", to: "return_tp53_mid", label: "10-19%" },
    { from: "tp53_blasts", to: "return_tp53_high", label: ">=20%" },
    { from: "step2", to: "step3", label: "No" },
    { from: "step3", to: "mut_blasts", label: "Yes" },
    { from: "mut_blasts", to: "return_mut_low", label: "<10%" },
    { from: "mut_blasts", to: "return_mut_mid", label: "10-19%" },
    { from: "mut_blasts", to: "return_mut_high", label: ">=20%" },
    { from: "step3", to: "step4", label: "No" },
    { from: "step4", to: "cyto_blasts", label: "Yes" },
    { from: "cyto_blasts", to: "return_cyto_low", label: "<10%" },
    { from: "cyto_blasts", to: "return_cyto_mid", label: "10-19%" },
    { from: "cyto_blasts", to: "return_cyto_high", label: ">=20%" },
    { from: "step4", to: "step4a", label: "No" },
    { from: "step4a", to: "mut_blasts", label: "Yes" },
    { from: "step4a", to: "step5", label: "No" },
    { from: "step5", to: "return_nos_low", label: "<10%" },
    { from: "step5", to: "return_nos_mid", label: "10-19%" },
    { from: "step5", to: "return_nos_high", label: ">=20%" },
  ],
};

// ── MDS WHO 2022 ────────────────────────────────────────────
// Matches classify_MDS_WHO2022() step order exactly

export const mdsWhoFlow = {
  title: "MDS Classification — WHO 2022",
  nodes: [
    { id: "input", label: "Patient Data", type: "input", description: "From AML non-AML sentinel" },
    { id: "step1", label: "Step 1: TP53 biallelic?", type: "decision", description: "2x mutations, +del(17p), +LOH, >=50% VAF (NO complex karyotype)" },
    { id: "return_tp53", label: "MDS with biallelic TP53", type: "output" },
    { id: "step2", label: "Step 2: Blasts >= 20%?", type: "decision" },
    { id: "return_not_mds", label: "Not MDS", type: "output", description: "Consider AML" },
    { id: "blast_high", label: "Blasts 5-19%?", type: "decision" },
    { id: "fibrotic", label: "Fibrotic (MF grade >=2)?", type: "decision" },
    { id: "return_fibrotic", label: "MDS, fibrotic", type: "output" },
    { id: "blast_range", label: "Blast range?", type: "decision" },
    { id: "return_ib1", label: "MDS-IB1", type: "output", description: "Blasts 5-9%" },
    { id: "return_ib2", label: "MDS-IB2", type: "output", description: "Blasts 10-19%" },
    { id: "step3", label: "Step 3: SF3B1?", type: "decision", description: "Excludes -7/del(7q), complex, del(5q)" },
    { id: "return_sf3b1", label: "MDS with low blasts and SF3B1", type: "output" },
    { id: "step4", label: "Step 4: Isolated del(5q)?", type: "decision", description: "Max 1 additional abnormality, excludes -7/del(7q)" },
    { id: "return_5q", label: "MDS with low blasts and isolated 5q-", type: "output" },
    { id: "step5", label: "Step 5: Hypoplastic?", type: "decision" },
    { id: "return_hypo", label: "MDS, hypoplastic", type: "output" },
    { id: "step6", label: "Step 6: Dysplastic lineages >= 1?", type: "decision" },
    { id: "return_low_blasts", label: "MDS with low blasts", type: "output" },
    { id: "return_unclass", label: "MDS, unclassifiable", type: "output", description: "MDT review recommended" },
  ],
  edges: [
    { from: "input", to: "step1" },
    { from: "step1", to: "return_tp53", label: "Yes" },
    { from: "step1", to: "step2", label: "No" },
    { from: "step2", to: "return_not_mds", label: "Yes" },
    { from: "step2", to: "blast_high", label: "No" },
    { from: "blast_high", to: "fibrotic", label: "Yes (5-19%)" },
    { from: "fibrotic", to: "return_fibrotic", label: "Yes" },
    { from: "fibrotic", to: "blast_range", label: "No" },
    { from: "blast_range", to: "return_ib1", label: "5-9%" },
    { from: "blast_range", to: "return_ib2", label: "10-19%" },
    { from: "blast_high", to: "step3", label: "No (<5%)" },
    { from: "step3", to: "return_sf3b1", label: "Yes (no exclusions)" },
    { from: "step3", to: "step4", label: "No / excluded" },
    { from: "step4", to: "return_5q", label: "Yes" },
    { from: "step4", to: "step5", label: "No" },
    { from: "step5", to: "return_hypo", label: "Yes" },
    { from: "step5", to: "step6", label: "No" },
    { from: "step6", to: "return_low_blasts", label: ">= 1" },
    { from: "step6", to: "return_unclass", label: "None" },
  ],
};

// ── MDS ICC 2022 ────────────────────────────────────────────
// Matches classify_MDS_ICC2022() step order exactly

export const mdsIccFlow = {
  title: "MDS Classification — ICC 2022",
  nodes: [
    { id: "input", label: "Patient Data", type: "input", description: "From AML non-AML sentinel" },
    { id: "step1", label: "Step 1: TP53 multi-hit?", type: "decision", description: "WHO criteria + >=10% VAF + complex karyotype" },
    { id: "return_tp53", label: "MDS with mutated TP53", type: "output" },
    { id: "step2", label: "Step 2: Blasts >= 20%?", type: "decision" },
    { id: "return_not_mds", label: "Not MDS", type: "output" },
    { id: "blast_5_9", label: "Blasts 5-9%?", type: "decision" },
    { id: "return_excess", label: "MDS with excess blasts", type: "output" },
    { id: "blast_10_19", label: "Blasts 10-19%?", type: "decision" },
    { id: "return_mds_aml", label: "MDS/AML", type: "output" },
    { id: "step3", label: "Step 3: SF3B1?", type: "decision", description: "Excludes -7/del(7q), complex, del(5q), RUNX1" },
    { id: "return_sf3b1", label: "MDS with mutated SF3B1", type: "output" },
    { id: "step4", label: "Step 4: del(5q)?", type: "decision", description: "Excludes concurrent -7/del(7q)" },
    { id: "return_5q", label: "MDS with del(5q)", type: "output" },
    { id: "step5", label: "Step 5: Hypoplastic?", type: "decision" },
    { id: "return_hypo", label: "MDS, hypoplastic", type: "output" },
    { id: "step6", label: "Step 6: Dysplastic lineages?", type: "decision" },
    { id: "return_single", label: "MDS, NOS single lineage", type: "output" },
    { id: "return_multi", label: "MDS, NOS multi-lineage", type: "output" },
    { id: "step7", label: "Step 7: Monosomy 7 / complex / MDS mutation?", type: "decision", description: "Without morphologic dysplasia" },
    { id: "return_nos_no_dys", label: "MDS, NOS without dysplasia", type: "output" },
    { id: "return_nos", label: "MDS, NOS", type: "output", description: "MDT review recommended" },
  ],
  edges: [
    { from: "input", to: "step1" },
    { from: "step1", to: "return_tp53", label: "Yes" },
    { from: "step1", to: "step2", label: "No" },
    { from: "step2", to: "return_not_mds", label: "Yes" },
    { from: "step2", to: "blast_10_19", label: "No" },
    { from: "blast_10_19", to: "return_mds_aml", label: "Yes" },
    { from: "blast_10_19", to: "blast_5_9", label: "No" },
    { from: "blast_5_9", to: "return_excess", label: "Yes" },
    { from: "blast_5_9", to: "step3", label: "No (<5%)" },
    { from: "step3", to: "return_sf3b1", label: "Yes (no exclusions)" },
    { from: "step3", to: "step4", label: "No / excluded" },
    { from: "step4", to: "return_5q", label: "Yes" },
    { from: "step4", to: "step5", label: "No" },
    { from: "step5", to: "return_hypo", label: "Yes" },
    { from: "step5", to: "step6", label: "No" },
    { from: "step6", to: "return_single", label: "1" },
    { from: "step6", to: "return_multi", label: ">= 2" },
    { from: "step6", to: "step7", label: "0 / none" },
    { from: "step7", to: "return_nos_no_dys", label: "Yes" },
    { from: "step7", to: "return_nos", label: "No" },
  ],
};

// ── CML WHO 2022 ────────────────────────────────────────────

export const cmlWhoFlow = {
  title: "CML — WHO 2022 (2 Phases)",
  nodes: [
    { id: "input", label: "BCR::ABL1+, blasts <20%", type: "input" },
    { id: "blast_check", label: "Blast Phase?", type: "decision", description: "Blasts >=20%, extramedullary blasts, MECOM rearr., lymphoblasts >5%" },
    { id: "blast", label: "Blast Phase", type: "output" },
    { id: "chronic", label: "Chronic Phase", type: "output", description: "High-risk features noted: basophils >=20%, additional cytogenetics, complex karyotype" },
  ],
  edges: [
    { from: "input", to: "blast_check" },
    { from: "blast_check", to: "blast", label: "Yes" },
    { from: "blast_check", to: "chronic", label: "No" },
  ],
};

// ── CML ICC 2022 ────────────────────────────────────────────

export const cmlIccFlow = {
  title: "CML — ICC 2022 (3 Phases)",
  nodes: [
    { id: "input", label: "BCR::ABL1+, blasts <20%", type: "input" },
    { id: "blast_check", label: "Blast Phase?", type: "decision", description: "Blasts >=20%, myeloid sarcoma, lymphoblasts >5%" },
    { id: "blast", label: "Blast Phase", type: "output" },
    { id: "accel_check", label: "Accelerated Phase?", type: "decision", description: "Blasts 10-19%, basophils >=20%, major-route ACAs (+Ph, +8, i(17q), +19, complex, 3q26.2)" },
    { id: "accel", label: "Accelerated Phase", type: "output" },
    { id: "chronic", label: "Chronic Phase", type: "output" },
  ],
  edges: [
    { from: "input", to: "blast_check" },
    { from: "blast_check", to: "blast", label: "Yes" },
    { from: "blast_check", to: "accel_check", label: "No" },
    { from: "accel_check", to: "accel", label: "Yes" },
    { from: "accel_check", to: "chronic", label: "No" },
  ],
};

// ── CMML ────────────────────────────────────────────────────

export const cmmlFlow = {
  title: "CMML Classification",
  nodes: [
    { id: "gate", label: "MDS Gate", type: "input", description: "Monocytosis detected" },
    { id: "collect", label: "UI Collects Data", type: "action", description: "Monocyte count, %, PB blasts, WBC, Auer rods, cytopenia (ICC)" },
    { id: "amc_check", label: "AMC >=0.5 and mono >=10%?", type: "decision" },
    { id: "not_cmml_1", label: "Not CMML", type: "output" },
    { id: "blast_check", label: "Blasts <20% (PB and BM)?", type: "decision" },
    { id: "not_cmml_2", label: "Not CMML", type: "output", description: "Consider AML" },
    { id: "exclusion", label: "Exclusions?", type: "decision", description: "BCR::ABL1, FIP1L1::PDGFRA, FGFR1, ETV6::ABL1, ETV6::SYK" },
    { id: "not_cmml_3", label: "Not CMML", type: "output", description: "CML or MLN-Eo" },
    { id: "amc_level", label: "AMC Level?", type: "decision" },
    { id: "standard", label: "Standard (>=1.0)", type: "process", description: ">=1 of: dysplasia, clonal mutation, clonal cytogenetics" },
    { id: "oligo", label: "Oligomonocytic (0.5-<1.0)", type: "process", description: "Both dysplasia AND clonality required" },
    { id: "not_cmml_4", label: "Not CMML", type: "output", description: "Supportive criteria not met" },
    { id: "subtype", label: "Subtype by Blasts", type: "decision" },
    { id: "cmml2", label: "CMML-2", type: "action", description: "PB >=5% or BM >=10% or Auer rods" },
    { id: "cmml1", label: "CMML-1", type: "action", description: "Otherwise" },
    { id: "wbc", label: "WBC Count", type: "decision" },
    { id: "mp", label: "MP-CMML", type: "output", description: "WBC >=13 x10^9/L" },
    { id: "md", label: "MD-CMML", type: "output", description: "WBC <13 x10^9/L" },
  ],
  edges: [
    { from: "gate", to: "collect" },
    { from: "collect", to: "amc_check" },
    { from: "amc_check", to: "not_cmml_1", label: "No" },
    { from: "amc_check", to: "blast_check", label: "Yes" },
    { from: "blast_check", to: "not_cmml_2", label: "No" },
    { from: "blast_check", to: "exclusion", label: "Yes" },
    { from: "exclusion", to: "not_cmml_3", label: "Found" },
    { from: "exclusion", to: "amc_level", label: "Clear" },
    { from: "amc_level", to: "standard", label: ">=1.0" },
    { from: "amc_level", to: "oligo", label: "0.5-<1.0" },
    { from: "standard", to: "subtype", label: "Met" },
    { from: "oligo", to: "subtype", label: "Met" },
    { from: "standard", to: "not_cmml_4", label: "Not met", dashed: true },
    { from: "oligo", to: "not_cmml_4", label: "Not met", dashed: true },
    { from: "subtype", to: "cmml2", label: "High blasts" },
    { from: "subtype", to: "cmml1", label: "Low blasts" },
    { from: "cmml2", to: "wbc" },
    { from: "cmml1", to: "wbc" },
    { from: "wbc", to: "mp", label: ">=13" },
    { from: "wbc", to: "md", label: "<13" },
  ],
};

// ── ELN 2022 Risk ───────────────────────────────────────────

export const elnFlow = {
  title: "ELN 2022 Risk Stratification",
  nodes: [
    { id: "input", label: "AML Diagnosis Confirmed", type: "input" },
    { id: "adverse_check", label: "Adverse markers?", type: "decision", description: "TP53, complex karyotype, -5/del(5q), -7, -17/abn(17p), t(6;9), inv(3)/t(3;3), KMT2A (not t(9;11)), MECOM, NUP98, BCR::ABL1" },
    { id: "return_adverse", label: "Adverse", type: "output", description: "Median OS ~8-10 months" },
    { id: "favorable_check", label: "Favorable markers?", type: "decision", description: "t(8;21), inv(16)/t(16;16), NPM1, CEBPA bZIP in-frame" },
    { id: "flt3_check", label: "FLT3-ITD present?", type: "decision", description: "Overrides favorable → intermediate" },
    { id: "return_favorable", label: "Favorable", type: "output", description: "Median OS >60 months" },
    { id: "return_intermediate", label: "Intermediate", type: "output", description: "Median OS ~16-24 months" },
    { id: "return_intermediate_default", label: "Intermediate", type: "output", description: "Default — no specific markers" },
  ],
  edges: [
    { from: "input", to: "adverse_check" },
    { from: "adverse_check", to: "return_adverse", label: "Yes" },
    { from: "adverse_check", to: "favorable_check", label: "No" },
    { from: "favorable_check", to: "flt3_check", label: "Yes" },
    { from: "flt3_check", to: "return_intermediate", label: "Yes" },
    { from: "flt3_check", to: "return_favorable", label: "No" },
    { from: "favorable_check", to: "return_intermediate_default", label: "No" },
  ],
};
